name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python for Backend
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies (Backend)
        run: |
          cd BackEnd
          pip install -r requirements.txt

      - name: Build Backend Docker Image
        run: |
          cd BackEnd
          docker build -t my-fastapi-backend .

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies (Frontend)
        run: |
          cd FrontEnd/chatify-front
          npm install

      - name: Build Frontend Docker Image
        run: |
          cd FrontEnd/chatify-front
          docker build -t my-react-frontend .
          
      - name: Run tests with pytest
        working-directory: BackEnd
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
        env:
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          pip install -r requirements.txt
          pytest tests/
