name: CI/CD

on:
  push:
  pull_request:

jobs:
  backend-and-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (Backend)
        run: |
          cd BackEnd
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage report
        working-directory: BackEnd
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
          ls -lh .

      - name: Verify coverage report
        working-directory: BackEnd
        run: test -f coverage.xml || (echo "Coverage report not found" && exit 1)

      - name: Debug Coverage Directory
        run: ls -lh BackEnd/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=agomep03_chatify
            -Dsonar.organization=agomep03
            -Dsonar.projectName=Chatify
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.version=3.10
            -Dsonar.python.coverage.reportPaths=BackEnd/coverage.xml

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies (Frontend)
        run: |
          cd FrontEnd/chatify-front
          npm install

      - name: Build Frontend Docker Image
        run: |
          cd FrontEnd/chatify-front
          docker build -t my-react-frontend .
